backend:
  name: github
  repo: razojhameas/personal-website
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "test"
    label: "Test Collection"
    files:
      - label: "Test Page"
        name: "test-page"
        file: "test.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }