backend:
  name: github
  repo: razojhameas/personal-website
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "About"
        name: "about"
        file: "about.html"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Projects"
        name: "projects"
        file: "projects.html"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Achievements"
        name: "achievements"
        file: "achievements.html"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Skills"
        name: "skills"
        file: "skills.html"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }